name: CI

on:
  push:
    branches:
      - 'feat/**'
      - dev
      - release
      - main
      - dev_hotfix
      - release_hotfix
  pull_request:
    branches:
      - dev
      - release
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Run tests
        run: npm test

      - name: Build (on dev/release/main)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release_hotfix') || startsWith(github.ref, 'refs/heads/dev_hotfix')
        run: |
          npm run build
      - name: Upload build artifact
        if: success() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release_hotfix') || startsWith(github.ref, 'refs/heads/dev_hotfix'))
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
