name: Deploy to Main (Prod)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - run: npm run build
      # Deploy to prod
      - name: Deploy to Vercel Prod
        id: deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: myapp.com
      # Rollback nếu deploy fail
      - name: Rollback on failure
        if: failure()
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          git checkout $LATEST_TAG
          git push origin main --force
          echo "Rolled back to $LATEST_TAG"